name: create-job-workflow
on: 
#  push:
  workflow_dispatch:
    inputs:
      GROUP:
        default: "kritifaujdar-rg"
      LOCATION:
        default: "westus"
      WORKSPACE:
        default: "kritifaujdar-ws"
  workflow_call:
    inputs:
      GROUP:
        default: "kritifaujdar-rg"
        type: string
      LOCATION:
        default: "westus"
        type: string
      WORKSPACE:
        default: "kritifaujdar-ws"
        type: string
    secrets:
      AZ_CREDS:
        required: true

env:
  GROUP: ${{ github.event.inputs.name.GROUP }}
  LOCATION: ${{ github.event.inputs.name.LOCATION }}
  WORKSPACE: ${{ github.event.inputs.name.WORKSPACE }}  

jobs:
  create-mljob-job:
    environment: 
      name: dev
      url: ${{ steps.create-job-step.outputs.RUNURI }}
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: setup
      run: bash setup.sh 
      working-directory: cli
    - name: create-job-step
      id: create-job-step 
      run: bash -x cli/create-job.sh src/pipeline/pipeline.yml
    outputs:
      MLJOB_RUNID: ${{ steps.create-job-step.outputs.RUNID }}
      MLJOB_RUNURI: ${{ steps.create-job-step.outputs.RUNURI }}
